### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by Kawai1Ace** [ChengpengLi1003/DotaMath#2]
请问作者什么时候可以分享一下论文的代码，谢谢

**Comment by ChengpengLi1003** [comment]
感谢关注，我会尽快把代码和数据开源出来的。

**Comment by rangmiao** [comment]
这篇工作很有意义，同时想请问作者什么时候可以分享一下论文的代码和数据

**Comment by dongguanting** [comment]
We released our ***DotaMathQA*** dataset! Download [DotaMathQA](https://drive.google.com/drive/folders/1Hwey6ovYU2ERVox76e-3JTsJBe_PHOl6?usp=sharing) here.
