### ISSUE TITLE
公式（6）$\tau$的理解

### ISSUE THREAD

**Issue by cingtiye** [ChengpengLi1003/DotaMath#3]
非常感谢（即将）开源这么棒的工作~
有个小问题想请教一下，公式（6）中的$\tau$我的理解是多轮的样本既包含正确的solution，也包含错误的solution，（当然还有纠正的过程）。按照公式（6）做监督学习的话，是正确和错误的solution都要学吗？
![image](https://github.com/user-attachments/assets/e72e6cfc-d77e-47e0-8a94-8142ebb57669)

**Comment by ChengpengLi1003** [comment]
感谢关注，对于学习纠错数据，是不是要把错误部分学进去，不同research的结论似乎不太一致，在具体训练时，可能都做了去比对会更好，我后续会更新比对的结果。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月12日(周二) 下午2:34
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ChengpengLi1003/DotaMath] 公式（6）$\tau$的理解 (Issue #3)




 
非常感谢（即将）开源这么棒的工作~
 有个小问题想请教一下，公式（6）中的$\tau$我的理解是多轮的样本既包含正确的solution，也包含错误的solution，（当然还有纠正的过程）。按照公式（6）做监督学习的话，是正确和错误的solution都要学吗？
 image.png (view on web)

**Comment by dongguanting** [comment]
We released our ***DotaMathQA*** dataset! Download [DotaMathQA](https://drive.google.com/drive/folders/1Hwey6ovYU2ERVox76e-3JTsJBe_PHOl6?usp=sharing) here.
